title: Frostq
description: "Página personal de Diego López Garciá. Estudiante de Ingeniería del Software."

author:
  name: Diego López
  twitter: diegolopgr
  github: Frostqui
  bio: Estudiando Software en la URJC. En esta página encontarás todo tipo de articulos y tutoriales sobre el desarrollo web y el mundo de la programación en general.




baseurl: 
exclude: ['README.md']
permalink: pretty

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
