title: Frostq - Blog de desarrollo web
description: Coding beers. Blog sobre desarrollo web y software.

author:
  name: Diego L칩pez
  twitter: Frostq_
  github: Frostqui
  bio: Estudiando Software en la URJC. En esta p치gina encontar치s todo tipo de articulos y tutoriales sobre el desarrollo web y el mundo de la programaci칩n en general.


languages: ["es", "en"]
default_lang: "es"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

baseurl: 
exclude: ['README.md']
permalink: :title

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-polyglot
  - jekyll-feed
